const disciplinas = {
  "ingles": "Inglês",
  "eda": "Estrutura de Dados e Algoritmos",
  "plp": "Paradigmas de Linguagem de Programação",
  "icc": "Introdução à Ciência da Computação",
  "infosoc": "Informática e Sociedade",
  "administracao": "Administração",
  "leda": "Laboratório de Estrutura de Dados e Algorítmos",
  "calculo1": "Cálculo 1",
  "calculo2": "Cálculo 2",
  "compiladores": "Compiladores",
  "bd2": "Banco de Dados 2",
  "ia": "Inteligência Artificial",
  "fmcc2": "Fundamentos da Matemática para Ciência da Computação 2",
  "so": "Sistemas Operacionais",
  "ic": "Introdução à Ciência da Computação",
  "redes": "Redes de Computadores",
  "prog1": "Programação 1",
  "bd1": "Banco de Dados 1",
  "labprog1": "Laboratório de Programação 1",
  "prog2": "Programação 2",
  "labprog2": "Laboratório de Programação 2",
  "fmcc1": "Fundamentos Matemáticos para Ciência da Computação 1",
  "metodologia": "Metodologia Científica",
  "adm-empreendedorismo": "Administração e Empreendedorismo",
  "daca": "Desenvolvimento de Aplicações Corporativas Avançadas",
  "prog-concorrente": "Programação Concorrente",
  "aa1": "Algoritmos Avançados I",
  "aa2": "Algoritmos Avançados II",
  "aa3": "Algoritmos Avançados III",
  "economia": "Economia",
  "tcc": "Trabalho de Conclusão de Curso",
  "proj-tcc": "Projeto de Trabalho de Conclusão de Curso",
  "grafos": "Teoria dos Grafos",
  "tcomp": "Teoria da Computação",
  "percepcao-comp": "Percepção Computacional",
  "direito-e-cidadania": "Direito e Cidadania",
  "lingua-portuguesa": "Lingua Portuguesa",
  "es": "Engenharia de Software",
  "linear": "Álgebra Linear",
  "vetorial": "Álgebra Linear e Geometria Analítica",
  "fisica1": "Física I",
  "fisica2": "Física II",
  "fisica3": "Física III",
  "irc/lirc": "Interconexão de Redes de Computadores/Laboratório de Interconexão de Redes de Computadores",
  "prog-funcional": "Programação Funcional",
  "adm-si": "Administração de Sistemas",
  "estatistica-aplicada": "Estatística Aplicada",
  "adsd": "Avaliação de Desempenho de Sistemas Discretos",
  "msn": "Métodos e Softwares Númericos",
  "rec-informacao": "Recuperação da Informação e Busca na Web",
  "intro-prob": "Introdução à Probabilidade",
  "empsoft": "Empreendedorismo em Software",
  "atal": "Análise e Técnicas de Algoritmos",
  "analise-sistemas": "Análise de Sistemas",
  "logica": "Lógica para computação",
  "v&v-testes": "Verificação e Validação de Software",
  "cnum": "Cálculo Numérico",
  "tecnicas-prog": "Técnicas de Programação",
  "eti": "Economia de Tecnologia da Informação",
  "proj2": "Projeto em Computação 2",
  "empreendedorismo": "Empreendedorismo em Software",
  "ciencia-dados-descritiva": "Ciência de Dados Preditiva",
  "gestao-ti": "Gestão de Tecnologia da Informação"
}

export default disciplinas;